Create diff comment from file to avoid size limit

diff --git a/.github/workflows/zz_generated.diff_helm_render_templates.yaml b/.github/workflows/zz_generated.diff_helm_render_templates.yaml
--- a/.github/workflows/zz_generated.diff_helm_render_templates.yaml
+++ b/.github/workflows/zz_generated.diff_helm_render_templates.yaml
@@ -100,26 +100,48 @@ jobs:
           done
       - name: get the diffs
         uses: mathiasvr/command-output@34408ea3d0528273faff3d9e201761ae96106cd0  # v2.0.0
-        id: diff
         with:
           run: |
-            found_differences=
-            first=1
-            for test_file_path in helm/${{ github.event.repository.name }}/ci/test-*-values.yaml; do
-              if [ "${first}" = 1 ]; then
-                first=
-              else
-                echo
-                echo
-              fi
-              echo "=== Differences when rendered with values file ${test_file_path} ==="
-              dyff between -s -i -b -g "/tmp/${test_file_path}/render-old.yaml" "/tmp/${test_file_path}/render-new.yaml" && echo "No difference" || { res=$?; found_differences=1; if [[ $res -eq 255 ]]; then echo "Diff error"; fi; }
-            done
+            marker="=== No differences at all ==="
+            (
+              found_differences=
+              first=1
+              for test_file_path in helm/${{ github.event.repository.name }}/ci/test-*-values.yaml; do
+                if [ "${first}" = 1 ]; then
+                  first=
+                else
+                  echo
+                  echo
+                fi
+                echo "=== Differences when rendered with values file ${test_file_path} ==="
+                dyff between -s -i -b -g "/tmp/${test_file_path}/render-old.yaml" "/tmp/${test_file_path}/render-new.yaml" && echo "No difference" || { res=$?; found_differences=1; if [[ $res -eq 255 ]]; then echo "Diff error"; fi; }
+              done
 
-            if [ -z "${found_differences}" ]; then
+              if [ -z "${found_differences}" ]; then
+                echo
+                echo
+                echo "${marker}"
+              fi
+            ) > /tmp/diffs
+
+            (
+              if ! grep -qF "${marker}" /tmp/diffs ; then
+                echo "**There were differences in the rendered Helm template, please check! ⚠️**"
+              else
+                echo "There were no differences in the rendered Helm template."
+              fi
+
               echo
-              echo "=== No differences at all ==="
-            fi
+              echo "<details>"
+              echo "<summary>Output</summary>"
+              echo "<!-- mandatory empty line -->"
+              echo ""
+              echo '```'
+              cat /tmp/diffs
+              echo '```'
+              echo "</details>"
+              echo "<!-- mandatory empty line -->"
+            ) > /tmp/comment-body
       - name: Find diff comment
         uses: peter-evans/find-comment@d5fe37641ad8451bdd80312415672ba26c86575e  # v3.0.0
         continue-on-error: true
@@ -136,37 +158,8 @@ jobs:
           type: delete
           comment_id: ${{ steps.fc.outputs.comment-id }}
           token: ${{ secrets.GITHUB_TOKEN }}
-      - name: Create comment in case of differences
+      - name: Create comment
         uses: peter-evans/create-or-update-comment@71345be0265236311c031f5c7866368bd1eff043  # v4.0.0
-        if: "!contains(steps.diff.outputs.stdout, '=== No differences at all ===')"
         with:
           issue-number: ${{ github.event.pull_request.number }}
-          body: |
-            **There were differences in the rendered Helm template, please check! ⚠️**
-
-            <details>
-            <summary>Output</summary>
-            <!-- mandatory empty line -->
-
-            ```
-            ${{ steps.diff.outputs.stdout }}
-            ```
-            </details>
-            <!-- mandatory empty line -->
-      - name: Create comment in case of no differences
-        uses: peter-evans/create-or-update-comment@71345be0265236311c031f5c7866368bd1eff043  # v4.0.0
-        if: "contains(steps.diff.outputs.stdout, '=== No differences at all ===')"
-        with:
-          issue-number: ${{ github.event.pull_request.number }}
-          body: |
-            There were no differences in the rendered Helm template.
-
-            <details>
-            <summary>Output</summary>
-            <!-- mandatory empty line -->
-
-            ```
-            ${{ steps.diff.outputs.stdout }}
-            ```
-            </details>
-            <!-- mandatory empty line -->
+          body-path: /tmp/comment-body
